apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: providerconfig-gcp
spec:
  projectID: cloud-native-experience-lab
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-credentials
      key: credentials