apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: aws-load-balancer-controller-crds
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./stable/aws-load-balancer-controller/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: aws-eks-charts
  validation: client