apiVersion: storage.gcp.crossplane.io/v1alpha3
kind: Bucket
metadata:
  name: crossplane-example-bucket
  annotations:
    # Note that this will be the actual bucket name so it has to be globally unique/available.
    crossplane.io/external-name: crossplane-example-bucket
spec:
  deletionPolicy: Delete
  location: EU
  storageClass: REGIONAL
  providerConfigRef:
    name: providerconfig-gcp